### ISSUE TITLE
Phased variant Plot

### ISSUE THREAD

**Issue by sharonnatashacox** [farhangus/Sniffles2_plot#11]
Does not recognize phased variants (0|1) when creating the plot: 
![del_ins_genotype_phased](https://github.com/farhangus/Sniffles2_plot/assets/77333448/efbece20-7523-43fb-accf-3c3bf817f2c7)
![del_ins_genotype_unphased](https://github.com/farhangus/Sniffles2_plot/assets/77333448/2e5a740e-dd33-4110-82ea-e2962ce29fb2)

**Comment by farhangus** [comment]
HI, will you please send me the sample of your VCF file, so I can check the results. email "fjaryanius@gmail.com"

**Comment by farhangus** [comment]
Thanks for your feedback, the feature for generating the phased plots are added. version 0.2.0

**Comment by sharonnatashacox** [comment]
[NO_FILTERED_PLOT_C_on_NO_phased.zip](https://github.com/user-attachments/files/16392662/NO_FILTERED_PLOT_C_on_NO_phased.zip)
[NO_FILTERED_PLOT_C_on_phased.zip](https://github.com/user-attachments/files/16392663/NO_FILTERED_PLOT_C_on_phased.zip)
Thank you for adding the feature for phased variants. The genotype frequency plot should contain the counts for phased variants. I have uploaded two zipped folders, one containing the results from a phased VCF and the other the results from the same vcf  but without phasing information. some of the plots are different , there should be consistency between the plots. Thank you in advance for your help
