### ISSUE TITLE
Plot multi-sample VCF file error encountered

### ISSUE THREAD

**Issue by liuyangzzu** [farhangus/Sniffles2_plot#13]
Hi,

I want to plot heatmap and upset figures of multiple samples in my VCF file, but the command failed.

Below is my command used and error message:

```
python3 -m sniffles2_plot -i aml_nanopore_all_samples_sniffles.vcf -o all_samples_plots

/projects/li-lab/yang/anaconda3/envs/sniffles/lib/python3.10/site-packages/sniffles2_plot/chart_generator/sv_sites_per_genome.py:119: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
An error occurred: string index out of range
```

**Comment by farhangus** [comment]
Hi, will you please sned me a sample VCF so, I can check the program. my email address is fjaryanius@gmail.com

**Comment by liuyangzzu** [comment]
Hi Farhangus,

Here I share you the input VCF file I used:
https://storage.googleapis.com/jax-nanopore-01-project-data/aml_nanopore_all_samples_sniffles.vcf.gz


Let me know if you have issue to access it.

Below is my command used and error message:

python3 -m sniffles2_plot -i aml_nanopore_all_samples_sniffles.vcf -o
all_samples_plots

/projects/li-lab/yang/anaconda3/envs/sniffles/lib/python3.10/site-packages/sniffles2_plot/chart_generator/sv_sites_per_genome.py:119:
UserWarning: set_ticklabels() should only be used with a fixed number of
ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels(ax.get_xticklabels(), fontweight="bold")
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
An error occurred: string index out of range

reference to issue link:
https://github.com/farhangus/Sniffles2_plot/issues/13

Thank you for your help!

Best
Yang

farhangus ***@***.***> 于2024年5月22日周三 16:20写道：

**Comment by farhangus** [comment]
Thanks for sending the file. I was checking your file and the problem is due to the lack of SUPP_VEC. In your VCF file, because of some reasons, there is no SUPP_VEC information, so the program cannot generate the related charts that are using SUPP_VEC.
